dataset: scifact
train_path: /projects/futhark1/data/wzm289/code/RLSeq2SeqPytorch/scifact/train.source_rl
reward: map
model_name: /projects/futhark1/data/wzm289/code/RLSeq2SeqPytorch/scifact_results_best/checkpoint-1068
model_save_path: scifact_results_map
txt_in_min_len: 2
txt_in_max_len: 8
txt_out_min_len: 4
txt_out_max_len: 16